### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ene1337** [clientlessx/Discord-Username-Checker#3]
problem : [DEBUG] Reponse: 400 Data: {'code': 50035, 'errors': {'password': {'_errors': [{'code': 'PASSWORD_DOES_NOT_MATCH', 'message': 'Invalid password.'}]}}, 'message': 'Invalid Form Body'}

**Comment by heavilyjammin** [comment]
yea mine says the same thing what does it mean 
"[DEBUG] Reponse: 400 Data: {'code': 50035, 'errors': {'password': {'_errors': [{'code': 'PASSWORD_DOES_NOT_MATCH', 'message': 'Password does not match.'}]}}, 'message': 'Invalid Form Body'}" please help me so I can get a new discord tag.

**Comment by clientlessx** [comment]
Discords end-point has changed the way data is sent back. You need to now have the name change option available to update for it to work
