### ISSUE TITLE
no password?

### ISSUE THREAD

**Issue by Jeep012** [clientlessx/Discord-Username-Checker#4]
[DEBUG] Reponse: 400 Data: {'code': 50035, 'errors': {'password': {'_errors': [{'code': 'PASSWORD_DOES_NOT_MATCH', 'message': 'Password does not match.'}]}}, 'message': 'Invalid Form Body'}

**Comment by lina2002uwu** [comment]
[DEBUG] Reponse: 400 Data: {'code': 50035, 'errors': {'password': {'_errors': [{'code': 'PASSWORD_DOES_NOT_MATCH', 'message': 'Password does not match.'}]}}, 'message': 'Invalid Form Body'}

**Comment by clientlessx** [comment]
There has been a new update to fix this issue
