### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by sami2341** [clientlessx/Discord-Username-Checker#5]
thank you for the update , can you make a way that i check my username list that i put in names.txt and simply check them ?

**Comment by xARMR** [comment]
i make it multi tokens and usernames.txt and proxies.txt with chatgpt nothing impossible

**Comment by clientlessx** [comment]
> i make it multi tokens and usernames.txt and proxies.txt with chatgpt nothing impossible

Using ChatGPT is a bad habit to get into...

**Comment by clientlessx** [comment]
> thank you for the update , can you make a way that i check my username list that i put in names.txt and simply check them ?

As this is NOT an issue, but a request i am closing this. I will update to suit your needs soon, please stay posted on the discord server for the update!
